/// Generated by AssetsRefGenerator on 2021/09/15
class Res {
  static const String api_empty = "assets/anim/api_empty.json";
  static const String api_error = "assets/anim/api_error.json";
  static const String ar = "assets/lang/ar.json";
  static const String delivery = "assets/anim/delivery.json";
  static const String empty_cart = "assets/anim/empty_cart.json";
  static const String en = "assets/lang/en.json";
  static const String following = "assets/images/following.png";
  static const String hands = "assets/images/hands.png";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoWhite = "assets/images/logoWhite.png";
  static const String marker = "assets/images/marker.png";
  static const String nodata = "assets/images/nodata.png";
  static const String placeholder = "assets/images/placeholder.png";
  static const String plus = "assets/images/plus.png";
  static const String splash = "assets/images/splash.png";
  static const String success = "assets/anim/success.json";
}
